# Generated by Django 4.1.1 on 2022-09-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Roastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('coffee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('flavour_1', models.CharField(max_length=30)),
                ('flavour_2', models.CharField(max_length=30)),
                ('flavour_3', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coffee_app.origin')),
                ('roast', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coffee_app.roast')),
                ('roastery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coffee_app.roastery')),
            ],
        ),
    ]
