# Generated by Django 4.1 on 2022-10-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0002_users_origin_country_roast_type_roastery_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='userscoffees',
            name='id',
        ),
        migrations.AddField(
            model_name='coffee',
            name='flavour_4',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='coffee',
            name='flavour_5',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='coffee',
            name='my_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='coffee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userscoffees',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
